### ISSUE TITLE
AdBlock

### ISSUE THREAD

**Issue by ghost** [pxtrez/quizizz-cheat#1]
swears at adblock even though it does not exist and I have never downloaded it.

**Comment by pxtrez** [comment]
Hey, If you could please give me your discord id, it would be great!

**Comment by ghost** [comment]
anti_query

**Comment by pxtrez** [comment]
I was not able to find your account. I need your discord username or userId

**Comment by ghost** [comment]
567474999045128193

**Comment by pxtrez** [comment]
sorry for so late response, haven't seen your reply. The problem should be gone for you
